name: jupvoibin
channels:
  - conda-forge
dependencies:
  - python
  - pandas
  - folium
  - ipyvolume
  - bqplot
  - scipy
  - ipympl
  - voila=0.1.20
  - ipympl
  - xleaflet=0.8.0
  - xeus-cling=0.6.0
